spring:
  application:
    name: todoapp
  datasource:
    url: jdbc:mysql://localhost:3306/todo-list
    username: root
    password: 88888888
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect